/*
 * This source file was generated by the Gradle 'init' task
 */
package com.poc.koog

import ai.koog.agents.core.agent.AIAgent
import ai.koog.prompt.executor.llms.all.simpleOllamaAIExecutor
import ai.koog.prompt.llm.OllamaModels
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
    val agent = AIAgent(
        executor = simpleOllamaAIExecutor(), // defaults to port 11434
        llmModel = OllamaModels.Meta.LLAMA_3_2,
        systemPrompt = """
            You are a helpful assistant. Answer user questions concisely.
        """.trimIndent()
    )
    val result = agent.runAndGetResult("Hello! how can you help me?")
    println("Agent Response: $result")
}
