import org.jetbrains.kotlin.konan.properties.Properties

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.build.config)
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    // Koog artifacts are hosted in the following URL.
    maven {
        url = uri("https://packages.jetbrains.team/maven/p/grazi/grazie-platform-public")
    }
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.koog.agents)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.poc.koog.AppKt"
}

buildConfig {
    val properties = Properties()
    rootProject.file("local.properties").reader().use { reader ->
        properties.load(reader)
        if (properties["file_tool_base_path"] == null) {
            throw IllegalArgumentException(
                """
                    Ensure that you set the `file_tool_base_path` in `local.properties`
                    Example:
                    file_tool_base_path=/path/to/poc-koog/app/src/main/kotlin/com/poc/koog
                """.trimIndent()
            )
        }
        buildConfigField("FILE_TOOL_BASE_PATH", File(properties["file_tool_base_path"] as String))
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
