from typing import Protocol, Any


class Logger(Protocol):
    def debug(self, msg, *args, **kwargs) -> None: ...

    def info(self, msg, *args, **kwargs) -> None: ...

    def warning(self, msg, *args, **kwargs) -> None: ...

    def error(self, msg, *args, **kwargs) -> None: ...

    def exception(self, msg, *args, exc_info=True, **kwargs) -> None: ...

    def critical(self, msg, *args, **kwargs) -> None: ...

    def fatal(self, msg, *args, **kwargs) -> None: ...

    def log(self, level, msg, *args, **kwargs) -> None: ...
